import { ThemeProvider } from "@/app/context/themeContext";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/app/components/Navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Usama's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} MainBody`}>
        <ThemeProvider>
          <div style={{ minHeight: "100%" }}>
            <NavbarComponent />
            <div style={{ height: "calc(100% - 15vh)" }}>
              {children}
              <SpeedInsights />
              <Analytics />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
